version: 0.0
os: linux
files:
  - source: /site.yml
    destination: /var/www/yml/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: ec2-user
    - location: scripts/start_server
      timeout: 300
      runas: ec2-user
      - location: deploy.sh
        runas: ec2-user
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: ec2-user
